# Site settings
title: "tokuhirom's notes."
email: tokuhirom@gmail.com
description: "Shut the fuck up and write some code"
baseurl: ""
url: "http://tokuhirom.github.io/wiki/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
